name: Merge Main to Deploy

on:
  push:
    branches:
      - main

jobs:
  merge-main-to-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    
    - name: Create and checkout deploy branch
      run: |
        git checkout -B deploy
        git pull origin deploy || true

    - name: Merge main into deploy
      run: |
        git merge --no-ff main
        git push origin deploy
