name: Merge Main to Deploy

on:
  push:
    branches:
      - main

jobs:
  merge-main-to-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Merge Main into Deploy
      uses: everlytic/branch-merge@1.1.2
      with:
        github_token: ${{ github.token }}
        source_ref: deploy
        target_branch: main
        commit_message_template: 'chore(deploy): merge main into deploy'